/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedUserProfileRouteImport } from './routes/_protected/user-profile'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AdminAdminPoliticalPartiesIndexRouteImport } from './routes/_admin/admin/political-parties/index'
import { Route as AdminAdminElectoralGeographiesIndexRouteImport } from './routes/_admin/admin/electoral-geographies/index'
import { Route as AdminAdminElectoralConstituenciesIndexRouteImport } from './routes/_admin/admin/electoral-constituencies/index'
import { Route as AdminAdminCandidatesIndexRouteImport } from './routes/_admin/admin/candidates/index'
import { Route as AdminAdminPoliticalPartiesAddRouteImport } from './routes/_admin/admin/political-parties/add'
import { Route as AdminAdminPoliticalPartiesPartyIdRouteImport } from './routes/_admin/admin/political-parties/$partyId'
import { Route as AdminAdminElectoralConstituenciesAddRouteImport } from './routes/_admin/admin/electoral-constituencies/add'
import { Route as AdminAdminElectoralConstituenciesConstituencyIdRouteImport } from './routes/_admin/admin/electoral-constituencies/$constituencyId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUserProfileRoute = ProtectedUserProfileRouteImport.update({
  id: '/user-profile',
  path: '/user-profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPoliticalPartiesIndexRoute =
  AdminAdminPoliticalPartiesIndexRouteImport.update({
    id: '/admin/political-parties/',
    path: '/admin/political-parties/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminElectoralGeographiesIndexRoute =
  AdminAdminElectoralGeographiesIndexRouteImport.update({
    id: '/admin/electoral-geographies/',
    path: '/admin/electoral-geographies/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminElectoralConstituenciesIndexRoute =
  AdminAdminElectoralConstituenciesIndexRouteImport.update({
    id: '/admin/electoral-constituencies/',
    path: '/admin/electoral-constituencies/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminCandidatesIndexRoute =
  AdminAdminCandidatesIndexRouteImport.update({
    id: '/admin/candidates/',
    path: '/admin/candidates/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminPoliticalPartiesAddRoute =
  AdminAdminPoliticalPartiesAddRouteImport.update({
    id: '/admin/political-parties/add',
    path: '/admin/political-parties/add',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminPoliticalPartiesPartyIdRoute =
  AdminAdminPoliticalPartiesPartyIdRouteImport.update({
    id: '/admin/political-parties/$partyId',
    path: '/admin/political-parties/$partyId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminElectoralConstituenciesAddRoute =
  AdminAdminElectoralConstituenciesAddRouteImport.update({
    id: '/admin/electoral-constituencies/add',
    path: '/admin/electoral-constituencies/add',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminElectoralConstituenciesConstituencyIdRoute =
  AdminAdminElectoralConstituenciesConstituencyIdRouteImport.update({
    id: '/admin/electoral-constituencies/$constituencyId',
    path: '/admin/electoral-constituencies/$constituencyId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/user-profile': typeof ProtectedUserProfileRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/electoral-constituencies/$constituencyId': typeof AdminAdminElectoralConstituenciesConstituencyIdRoute
  '/admin/electoral-constituencies/add': typeof AdminAdminElectoralConstituenciesAddRoute
  '/admin/political-parties/$partyId': typeof AdminAdminPoliticalPartiesPartyIdRoute
  '/admin/political-parties/add': typeof AdminAdminPoliticalPartiesAddRoute
  '/admin/candidates': typeof AdminAdminCandidatesIndexRoute
  '/admin/electoral-constituencies': typeof AdminAdminElectoralConstituenciesIndexRoute
  '/admin/electoral-geographies': typeof AdminAdminElectoralGeographiesIndexRoute
  '/admin/political-parties': typeof AdminAdminPoliticalPartiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/user-profile': typeof ProtectedUserProfileRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/electoral-constituencies/$constituencyId': typeof AdminAdminElectoralConstituenciesConstituencyIdRoute
  '/admin/electoral-constituencies/add': typeof AdminAdminElectoralConstituenciesAddRoute
  '/admin/political-parties/$partyId': typeof AdminAdminPoliticalPartiesPartyIdRoute
  '/admin/political-parties/add': typeof AdminAdminPoliticalPartiesAddRoute
  '/admin/candidates': typeof AdminAdminCandidatesIndexRoute
  '/admin/electoral-constituencies': typeof AdminAdminElectoralConstituenciesIndexRoute
  '/admin/electoral-geographies': typeof AdminAdminElectoralGeographiesIndexRoute
  '/admin/political-parties': typeof AdminAdminPoliticalPartiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_protected/user-profile': typeof ProtectedUserProfileRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/electoral-constituencies/$constituencyId': typeof AdminAdminElectoralConstituenciesConstituencyIdRoute
  '/_admin/admin/electoral-constituencies/add': typeof AdminAdminElectoralConstituenciesAddRoute
  '/_admin/admin/political-parties/$partyId': typeof AdminAdminPoliticalPartiesPartyIdRoute
  '/_admin/admin/political-parties/add': typeof AdminAdminPoliticalPartiesAddRoute
  '/_admin/admin/candidates/': typeof AdminAdminCandidatesIndexRoute
  '/_admin/admin/electoral-constituencies/': typeof AdminAdminElectoralConstituenciesIndexRoute
  '/_admin/admin/electoral-geographies/': typeof AdminAdminElectoralGeographiesIndexRoute
  '/_admin/admin/political-parties/': typeof AdminAdminPoliticalPartiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/user-profile'
    | '/admin'
    | '/admin/electoral-constituencies/$constituencyId'
    | '/admin/electoral-constituencies/add'
    | '/admin/political-parties/$partyId'
    | '/admin/political-parties/add'
    | '/admin/candidates'
    | '/admin/electoral-constituencies'
    | '/admin/electoral-geographies'
    | '/admin/political-parties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/user-profile'
    | '/admin'
    | '/admin/electoral-constituencies/$constituencyId'
    | '/admin/electoral-constituencies/add'
    | '/admin/political-parties/$partyId'
    | '/admin/political-parties/add'
    | '/admin/candidates'
    | '/admin/electoral-constituencies'
    | '/admin/electoral-geographies'
    | '/admin/political-parties'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_protected'
    | '/auth'
    | '/_protected/user-profile'
    | '/_admin/admin/'
    | '/_admin/admin/electoral-constituencies/$constituencyId'
    | '/_admin/admin/electoral-constituencies/add'
    | '/_admin/admin/political-parties/$partyId'
    | '/_admin/admin/political-parties/add'
    | '/_admin/admin/candidates/'
    | '/_admin/admin/electoral-constituencies/'
    | '/_admin/admin/electoral-geographies/'
    | '/_admin/admin/political-parties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/user-profile': {
      id: '/_protected/user-profile'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof ProtectedUserProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/political-parties/': {
      id: '/_admin/admin/political-parties/'
      path: '/admin/political-parties'
      fullPath: '/admin/political-parties'
      preLoaderRoute: typeof AdminAdminPoliticalPartiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/electoral-geographies/': {
      id: '/_admin/admin/electoral-geographies/'
      path: '/admin/electoral-geographies'
      fullPath: '/admin/electoral-geographies'
      preLoaderRoute: typeof AdminAdminElectoralGeographiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/electoral-constituencies/': {
      id: '/_admin/admin/electoral-constituencies/'
      path: '/admin/electoral-constituencies'
      fullPath: '/admin/electoral-constituencies'
      preLoaderRoute: typeof AdminAdminElectoralConstituenciesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/candidates/': {
      id: '/_admin/admin/candidates/'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminAdminCandidatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/political-parties/add': {
      id: '/_admin/admin/political-parties/add'
      path: '/admin/political-parties/add'
      fullPath: '/admin/political-parties/add'
      preLoaderRoute: typeof AdminAdminPoliticalPartiesAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/political-parties/$partyId': {
      id: '/_admin/admin/political-parties/$partyId'
      path: '/admin/political-parties/$partyId'
      fullPath: '/admin/political-parties/$partyId'
      preLoaderRoute: typeof AdminAdminPoliticalPartiesPartyIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/electoral-constituencies/add': {
      id: '/_admin/admin/electoral-constituencies/add'
      path: '/admin/electoral-constituencies/add'
      fullPath: '/admin/electoral-constituencies/add'
      preLoaderRoute: typeof AdminAdminElectoralConstituenciesAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/electoral-constituencies/$constituencyId': {
      id: '/_admin/admin/electoral-constituencies/$constituencyId'
      path: '/admin/electoral-constituencies/$constituencyId'
      fullPath: '/admin/electoral-constituencies/$constituencyId'
      preLoaderRoute: typeof AdminAdminElectoralConstituenciesConstituencyIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminElectoralConstituenciesConstituencyIdRoute: typeof AdminAdminElectoralConstituenciesConstituencyIdRoute
  AdminAdminElectoralConstituenciesAddRoute: typeof AdminAdminElectoralConstituenciesAddRoute
  AdminAdminPoliticalPartiesPartyIdRoute: typeof AdminAdminPoliticalPartiesPartyIdRoute
  AdminAdminPoliticalPartiesAddRoute: typeof AdminAdminPoliticalPartiesAddRoute
  AdminAdminCandidatesIndexRoute: typeof AdminAdminCandidatesIndexRoute
  AdminAdminElectoralConstituenciesIndexRoute: typeof AdminAdminElectoralConstituenciesIndexRoute
  AdminAdminElectoralGeographiesIndexRoute: typeof AdminAdminElectoralGeographiesIndexRoute
  AdminAdminPoliticalPartiesIndexRoute: typeof AdminAdminPoliticalPartiesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminElectoralConstituenciesConstituencyIdRoute:
    AdminAdminElectoralConstituenciesConstituencyIdRoute,
  AdminAdminElectoralConstituenciesAddRoute:
    AdminAdminElectoralConstituenciesAddRoute,
  AdminAdminPoliticalPartiesPartyIdRoute:
    AdminAdminPoliticalPartiesPartyIdRoute,
  AdminAdminPoliticalPartiesAddRoute: AdminAdminPoliticalPartiesAddRoute,
  AdminAdminCandidatesIndexRoute: AdminAdminCandidatesIndexRoute,
  AdminAdminElectoralConstituenciesIndexRoute:
    AdminAdminElectoralConstituenciesIndexRoute,
  AdminAdminElectoralGeographiesIndexRoute:
    AdminAdminElectoralGeographiesIndexRoute,
  AdminAdminPoliticalPartiesIndexRoute: AdminAdminPoliticalPartiesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProtectedRouteChildren {
  ProtectedUserProfileRoute: typeof ProtectedUserProfileRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedUserProfileRoute: ProtectedUserProfileRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
