/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AdminAdminPoliticalPartiesIndexRouteImport } from './routes/_admin/admin/political-parties/index'
import { Route as AdminAdminElectoralGeographiesIndexRouteImport } from './routes/_admin/admin/electoral-geographies/index'
import { Route as AdminAdminPoliticalPartiesAddRouteImport } from './routes/_admin/admin/political-parties/add'
import { Route as AdminAdminPoliticalPartiesPartyIdRouteImport } from './routes/_admin/admin/political-parties/$partyId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPoliticalPartiesIndexRoute =
  AdminAdminPoliticalPartiesIndexRouteImport.update({
    id: '/admin/political-parties/',
    path: '/admin/political-parties/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminElectoralGeographiesIndexRoute =
  AdminAdminElectoralGeographiesIndexRouteImport.update({
    id: '/admin/electoral-geographies/',
    path: '/admin/electoral-geographies/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminPoliticalPartiesAddRoute =
  AdminAdminPoliticalPartiesAddRouteImport.update({
    id: '/admin/political-parties/add',
    path: '/admin/political-parties/add',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminPoliticalPartiesPartyIdRoute =
  AdminAdminPoliticalPartiesPartyIdRouteImport.update({
    id: '/admin/political-parties/$partyId',
    path: '/admin/political-parties/$partyId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin': typeof AdminAdminIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/admin/political-parties/$partyId': typeof AdminAdminPoliticalPartiesPartyIdRoute
  '/admin/political-parties/add': typeof AdminAdminPoliticalPartiesAddRoute
  '/admin/electoral-geographies': typeof AdminAdminElectoralGeographiesIndexRoute
  '/admin/political-parties': typeof AdminAdminPoliticalPartiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin': typeof AdminAdminIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/admin/political-parties/$partyId': typeof AdminAdminPoliticalPartiesPartyIdRoute
  '/admin/political-parties/add': typeof AdminAdminPoliticalPartiesAddRoute
  '/admin/electoral-geographies': typeof AdminAdminElectoralGeographiesIndexRoute
  '/admin/political-parties': typeof AdminAdminPoliticalPartiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_admin/admin/political-parties/$partyId': typeof AdminAdminPoliticalPartiesPartyIdRoute
  '/_admin/admin/political-parties/add': typeof AdminAdminPoliticalPartiesAddRoute
  '/_admin/admin/electoral-geographies/': typeof AdminAdminElectoralGeographiesIndexRoute
  '/_admin/admin/political-parties/': typeof AdminAdminPoliticalPartiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/profile'
    | '/admin/political-parties/$partyId'
    | '/admin/political-parties/add'
    | '/admin/electoral-geographies'
    | '/admin/political-parties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/profile'
    | '/admin/political-parties/$partyId'
    | '/admin/political-parties/add'
    | '/admin/electoral-geographies'
    | '/admin/political-parties'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_protected'
    | '/auth/'
    | '/_admin/admin/'
    | '/_protected/profile/'
    | '/_admin/admin/political-parties/$partyId'
    | '/_admin/admin/political-parties/add'
    | '/_admin/admin/electoral-geographies/'
    | '/_admin/admin/political-parties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/political-parties/': {
      id: '/_admin/admin/political-parties/'
      path: '/admin/political-parties'
      fullPath: '/admin/political-parties'
      preLoaderRoute: typeof AdminAdminPoliticalPartiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/electoral-geographies/': {
      id: '/_admin/admin/electoral-geographies/'
      path: '/admin/electoral-geographies'
      fullPath: '/admin/electoral-geographies'
      preLoaderRoute: typeof AdminAdminElectoralGeographiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/political-parties/add': {
      id: '/_admin/admin/political-parties/add'
      path: '/admin/political-parties/add'
      fullPath: '/admin/political-parties/add'
      preLoaderRoute: typeof AdminAdminPoliticalPartiesAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/political-parties/$partyId': {
      id: '/_admin/admin/political-parties/$partyId'
      path: '/admin/political-parties/$partyId'
      fullPath: '/admin/political-parties/$partyId'
      preLoaderRoute: typeof AdminAdminPoliticalPartiesPartyIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminPoliticalPartiesPartyIdRoute: typeof AdminAdminPoliticalPartiesPartyIdRoute
  AdminAdminPoliticalPartiesAddRoute: typeof AdminAdminPoliticalPartiesAddRoute
  AdminAdminElectoralGeographiesIndexRoute: typeof AdminAdminElectoralGeographiesIndexRoute
  AdminAdminPoliticalPartiesIndexRoute: typeof AdminAdminPoliticalPartiesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminPoliticalPartiesPartyIdRoute:
    AdminAdminPoliticalPartiesPartyIdRoute,
  AdminAdminPoliticalPartiesAddRoute: AdminAdminPoliticalPartiesAddRoute,
  AdminAdminElectoralGeographiesIndexRoute:
    AdminAdminElectoralGeographiesIndexRoute,
  AdminAdminPoliticalPartiesIndexRoute: AdminAdminPoliticalPartiesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProtectedRouteChildren {
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
