// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NepalVotes.Infrastructure.Persistence;

#nullable disable

namespace NepalVotes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260127183702_addedCandidateSymbolTable")]
    partial class addedCandidateSymbolTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NepalVotes.Domain.Candidates.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<int?>("CandidateSymbolId")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsIndependent")
                        .HasColumnType("bit");

                    b.Property<int?>("PoliticalPartyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId");

                    b.HasIndex("CandidateSymbolId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("ConstituencyId", "CandidateSymbolId")
                        .IsUnique()
                        .HasFilter("[CandidateSymbolId] IS NOT NULL");

                    b.HasIndex("ConstituencyId", "PoliticalPartyId")
                        .IsUnique()
                        .HasFilter("[PoliticalPartyId] IS NOT NULL");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("NepalVotes.Domain.Candidates.CandidateSymbol", b =>
                {
                    b.Property<int>("CandidateSymbolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateSymbolId"));

                    b.Property<int>("CandidateSymbolMediaFileId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("CandidateSymbolId");

                    b.HasIndex("CandidateSymbolMediaFileId")
                        .IsUnique();

                    b.ToTable("CandidateSymbols");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralConstituencies.Constituency", b =>
                {
                    b.Property<int>("ConstituencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConstituencyId"));

                    b.Property<string>("ConstituencyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ConstituencyId");

                    b.HasIndex("ConstituencyName")
                        .IsUnique();

                    b.ToTable("Constituencies");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("DistrictId");

                    b.HasIndex("DistrictName")
                        .IsUnique();

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.Municipality", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MunicipalityId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MunicipalityType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("MunicipalityId");

                    b.HasIndex("DistrictId", "MunicipalityName")
                        .IsUnique();

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.VotingPlace", b =>
                {
                    b.Property<int>("VotingPlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VotingPlaceId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VotingPlaceAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("VotingPlaceId");

                    b.HasIndex("WardId", "VotingPlaceAddress")
                        .IsUnique();

                    b.ToTable("VotingPlaces");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.Ward", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardId"));

                    b.Property<int?>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WardNumber")
                        .HasColumnType("int");

                    b.HasKey("WardId");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("MunicipalityId", "WardName")
                        .IsUnique();

                    b.HasIndex("MunicipalityId", "WardNumber")
                        .IsUnique();

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("NepalVotes.Domain.MediaFiles.MediaFile", b =>
                {
                    b.Property<int>("MediaFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaFileId"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("MediaFileId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("NepalVotes.Domain.PoliticalParties.PoliticalParty", b =>
                {
                    b.Property<int>("PoliticalPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliticalPartyId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("PartyLeaderId")
                        .HasColumnType("int");

                    b.Property<string>("PoliticalPartyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SymbolMediaFileId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PoliticalPartyId");

                    b.HasIndex("PartyLeaderId")
                        .IsUnique();

                    b.HasIndex("SymbolMediaFileId")
                        .IsUnique();

                    b.ToTable("PoliticalParties");
                });

            modelBuilder.Entity("NepalVotes.Domain.Users.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NepalVotes.Domain.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ApprovedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("([FirstName] + ' ' + ISNULL([MiddleName], '') + ' ' + [LastName])", true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("RequestDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserRefreshTokenId")
                        .HasColumnType("int");

                    b.Property<int>("VotingPlaceId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_User_FullName");

                    b.HasIndex("VotingPlaceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NepalVotes.Domain.Users.UserDocument", b =>
                {
                    b.Property<int>("UserDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDocumentId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserDocumentMediaFileId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserDocumentId");

                    b.HasIndex("UserDocumentMediaFileId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserDocuments");
                });

            modelBuilder.Entity("NepalVotes.Domain.Users.UserOtp", b =>
                {
                    b.Property<int>("UserOtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserOtpId"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HashedOtpCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserOtpType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("UserOtpId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOtps");
                });

            modelBuilder.Entity("NepalVotes.Domain.Users.UserRefreshToken", b =>
                {
                    b.Property<int>("UserRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRefreshTokenId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("RefreshTokenExpiryTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRefreshTokenId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("NepalVotes.Domain.VotingResults.Vote", b =>
                {
                    b.Property<long>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VoteId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VotedFromLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VoteId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesRoleId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("RolesRoleId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("NepalVotes.Domain.Candidates.Candidate", b =>
                {
                    b.HasOne("NepalVotes.Domain.Candidates.CandidateSymbol", "CandidateSymbol")
                        .WithMany("Candidates")
                        .HasForeignKey("CandidateSymbolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NepalVotes.Domain.ElectoralConstituencies.Constituency", "Constituency")
                        .WithMany("Candidates")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NepalVotes.Domain.PoliticalParties.PoliticalParty", "PoliticalParty")
                        .WithMany("Candidates")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NepalVotes.Domain.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("NepalVotes.Domain.Candidates.Candidate", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateSymbol");

                    b.Navigation("Constituency");

                    b.Navigation("PoliticalParty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NepalVotes.Domain.Candidates.CandidateSymbol", b =>
                {
                    b.HasOne("NepalVotes.Domain.MediaFiles.MediaFile", "CandidateSymbolMediaFile")
                        .WithOne()
                        .HasForeignKey("NepalVotes.Domain.Candidates.CandidateSymbol", "CandidateSymbolMediaFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateSymbolMediaFile");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.District", b =>
                {
                    b.HasOne("NepalVotes.Domain.ElectoralGeographies.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.Municipality", b =>
                {
                    b.HasOne("NepalVotes.Domain.ElectoralGeographies.District", "District")
                        .WithMany("Municipalities")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.VotingPlace", b =>
                {
                    b.HasOne("NepalVotes.Domain.ElectoralGeographies.Ward", "Ward")
                        .WithMany("VotingPlaces")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.Ward", b =>
                {
                    b.HasOne("NepalVotes.Domain.ElectoralConstituencies.Constituency", "Constituency")
                        .WithMany("Wards")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NepalVotes.Domain.ElectoralGeographies.Municipality", "Municipality")
                        .WithMany("Wards")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("NepalVotes.Domain.PoliticalParties.PoliticalParty", b =>
                {
                    b.HasOne("NepalVotes.Domain.Users.User", "PartyLeader")
                        .WithOne()
                        .HasForeignKey("NepalVotes.Domain.PoliticalParties.PoliticalParty", "PartyLeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NepalVotes.Domain.MediaFiles.MediaFile", "SymbolMediaFile")
                        .WithOne()
                        .HasForeignKey("NepalVotes.Domain.PoliticalParties.PoliticalParty", "SymbolMediaFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartyLeader");

                    b.Navigation("SymbolMediaFile");
                });

            modelBuilder.Entity("NepalVotes.Domain.Users.User", b =>
                {
                    b.HasOne("NepalVotes.Domain.Users.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NepalVotes.Domain.ElectoralGeographies.VotingPlace", "VotingPlace")
                        .WithMany()
                        .HasForeignKey("VotingPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("VotingPlace");
                });

            modelBuilder.Entity("NepalVotes.Domain.Users.UserDocument", b =>
                {
                    b.HasOne("NepalVotes.Domain.MediaFiles.MediaFile", "UserDocumentMediaFile")
                        .WithOne()
                        .HasForeignKey("NepalVotes.Domain.Users.UserDocument", "UserDocumentMediaFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NepalVotes.Domain.Users.User", "User")
                        .WithMany("UserDocuments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserDocumentMediaFile");
                });

            modelBuilder.Entity("NepalVotes.Domain.Users.UserOtp", b =>
                {
                    b.HasOne("NepalVotes.Domain.Users.User", "User")
                        .WithMany("UserOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NepalVotes.Domain.Users.UserRefreshToken", b =>
                {
                    b.HasOne("NepalVotes.Domain.Users.User", "User")
                        .WithOne("UserRefreshToken")
                        .HasForeignKey("NepalVotes.Domain.Users.UserRefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NepalVotes.Domain.VotingResults.Vote", b =>
                {
                    b.HasOne("NepalVotes.Domain.Candidates.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NepalVotes.Domain.ElectoralConstituencies.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("NepalVotes.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NepalVotes.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NepalVotes.Domain.Candidates.CandidateSymbol", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralConstituencies.Constituency", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.District", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.Municipality", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("NepalVotes.Domain.ElectoralGeographies.Ward", b =>
                {
                    b.Navigation("VotingPlaces");
                });

            modelBuilder.Entity("NepalVotes.Domain.PoliticalParties.PoliticalParty", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("NepalVotes.Domain.Users.User", b =>
                {
                    b.Navigation("UserDocuments");

                    b.Navigation("UserOtps");

                    b.Navigation("UserRefreshToken")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
