<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NepalVotes.Application\NepalVotes.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ElectoralGeographies\" />
      <Folder Include="MediaFiles\" />
      <Folder Include="PoliticalParties\" />
      <Folder Include="Users\" />
    </ItemGroup>

</Project>
